# Use root/example as user/password credentials
# Configuração padrão: https://hub.docker.com/_/mongo
version: '3.1'

services:

  mongo: # DB
    image: mongo
    restart: always
    ports:
      - 27017:27017 # Expondo a porta do MONGODB, se estiver no mesmo container não precisa expor
    environment: # USER e PASSWORD para conectar no banco
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express: # IDEA DB
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment: # USER e PASSWORD para conectar na IDEA
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/